sudo: required
language: node_js
apt:
    sources:
        - google-chrome
    packages:
        - google-chrome-stable
        - google-chrome-beta
node_js:
    - "9.8.0"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
    - npm install -g angular-cli
    - npm install -g karma
    - npm install
    - ng build
services:
    - mysql
before_script:
    - mysql -e "CREATE DATABASE test" -u root
script:
    - npm run test-backend
    - karma start karma.conf.js --single-run
