sudo: required
language: node_js
apt:
    sources:
        - google-chrome
    packages:
        - google-chrome-stable
        - google-chrome-beta
node_js:
    - "9.8.0"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install --user codecov
install:
    - npm install codecov -g
    - npm install
    - ./node_modules/.bin/ng build
services:
    - mysql
script:
    - npm run test-all
after_success:
    - bash <(curl -s https://codecov.io/bash)